apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        auth_basic           "basic auth";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location / {
            root   /var/www/html;
            index  index.html index.htm;
        }
    }
